# Version 0.0.1
FROM ubuntu:16.04
MAINTAINER Sergio F. Gonzalez "sergio.f.gonzalez@gmail.com"
ENV REFRESHED_AT 2017-01-25

SHELL ["/bin/bash"]

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "echo SHELL=$SHELL"]
