#
## Application Properties
#

logger:
  format: "dev" #":date[iso] :method :url :status :response-time msec"

server:
  port: 5000
  public: "public"

app:
  entriesPerPage: 3

db:
  host: redis-db
  port: 6379

ERROR_ROUTE: true