# Resource descriptor for a Job definition
# using completions to specify how many times i want the job to run 

apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-batch-app-with-deadline

spec:
  activeDeadlineSeconds: 10
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: nodejs-batch-app-with-deadline
    spec:
      restartPolicy: OnFailure      
      containers:
      - name: nodejs-batch-job
        image: sergiofgonzalez/nodejs-batch-app