apiVersion: v1
kind: Pod
metadata:
  name: nodejs-sysdata-webapp-yml-labels-annotations
  labels:
    creation_method: manual
    env: prod
  annotations:
    com.github.sergiofgonzalez/description: "Node.js webapp with labels and annotations"
spec:
  containers:
    - image: sergiofgonzalez/nodejs-sysdata-webapp:v1
      name: nodejs-sysdata-webapp
      ports:
        - containerPort: 8080  # This is purely information and has no effect on whether the client can connect or not
          protocol: TCP
