# Version 0.0.1
FROM ubuntu:16.04
MAINTAINER Sergio F. Gonzalez "sergio.f.gonzalez@gmail.com"
ENV REFRESHED_AT 2017-01-25

STOPSIGNAL SIGKILL

ENTRYPOINT ["/bin/sh"]
CMD ["-c", "while true; do echo hello world; sleep 10; done"]
