## Manifest for a Service abstracting the Pod network address

# Version of the Kubernetes API and type of resource
apiVersion: v1
kind: Service

# Metadata for the resource with name (mandatory) and labels (optional)
metadata:
  name: sleep-2   # identifies the friendly name for the pod network address

# Specification of the resource. The actual structure depends on the resource
# being created.
# For the service, the selector and ports specification are required.

spec:
  selector:
    app: sleep-2  # matches all Pods labeled as `app: sleep-2`

  ports:
    - port: 80 # listens to port 80 and sends to port 80 on the pod