apiVersion: v1
kind: Pod
metadata:
  name: nodejs-sysdata-webapp-yml
  labels:
    creation_method: manual
    env: prod
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - image: sergiofgonzalez/nodejs-sysdata-webapp:v1
      name: nodejs-sysdata-webapp
      ports:
        - containerPort: 8080  # This is purely information and has no effect on whether the client can connect or not
          protocol: TCP
