# Resource Descriptor for a Replication Controller
# in charge of nodejs-sysdata pods

apiVersion: v1
kind: ReplicationController

metadata:
  name: nodejs-sysdata-webapp-rc

spec:
  replicas: 3
# selector:
#   app: nodejs-sysdata-webapp  # it's a best practice to get rc label from pod descriptor instead

  template:
    metadata:
      labels:
        app: nodejs-sysdata-webapp
    spec:
      containers:
        - name: nodejs-sysdata-webapp
          image: sergiofgonzalez/nodejs-sysdata-webapp:v1
          ports:
            - containerPort: 8080