## Manifest for sleep-1 deployment

apiVersion: apps/v1
kind: Deployment

metadata:
  name: sleep-1

spec:
  selector:
    matchLabels:
      app: sleep-1

  template:
    metadata:
      labels:
        app: sleep-1

    spec:
      containers:
        - name: sleeping-container
          image: sergiofgonzalez/sleeping-container:latest
