# Version 0.0.1
FROM ubuntu:16.04
MAINTAINER Sergio F. Gonzalez "sergio.f.gonzalez@gmail.com"
ENV REFRESHED_AT 2017-01-25
ENV MY_ENV_VAR "someValue"

# You can have several environment variables in one line
ENV DB_HOST=mysql DB_PORT=3306

ENTRYPOINT echo $MY_ENV_VAR $DB_HOST $DB_PORT